import { formatCep, formatCnpj } from "@/utils/format-field.util";
import {
  CEP_MASK,
  CNAE_MASK,
  CNPJ_MASK,
  CURRENCY_MASK,
  PHONE_MASK,
  UF_MASK,
  UPPERCASE_MASK,
  digitsMask,
} from "@/utils/input-mask.util";

// Recursos exibidos nos widgets do dashboard. `editableFields` espelha os
// UPDATABLE_FIELDS do backend; `fieldTypes` define o input de cada campo no
// modal de edição (campos sem tipo são texto); `fieldMasks` a máscara de
// exibição; `readOnlyFields` aparecem no formulário mas não são alterados.
// `idMask` é a máscara do campo de cadastro de um novo item.
export const RECORD_RESOURCES = {
  cep: {
    key: "cep",
    title: "CEP",
    label: "CEP",
    path: "/cep",
    listKey: "ceps",
    formatId: formatCep,
    idMask: CEP_MASK,
    columns: [
      { key: "street", header: "Logradouro" },
      { key: "neighborhood", header: "Bairro" },
      { key: "city", header: "Cidade" },
      { key: "uf", header: "UF" },
    ],
    editableFields: [
      "street",
      "complement",
      "unit",
      "neighborhood",
      "city",
      "uf",
      "state",
      "region",
      "ibgeCode",
      "giaCode",
      "ddd",
      "siafiCode",
    ],
    fieldTypes: {},
    fieldMasks: {
      uf: UF_MASK,
      ibgeCode: digitsMask(7),
      giaCode: digitsMask(10),
      ddd: digitsMask(2),
      siafiCode: digitsMask(10),
    },
    readOnlyFields: [],
  },
  cnpj: {
    key: "cnpj",
    title: "CNPJ",
    label: "CNPJ",
    path: "/cnpj",
    listKey: "cnpjs",
    formatId: formatCnpj,
    idMask: CNPJ_MASK,
    columns: [
      { key: "corporateName", header: "Razão social" },
      { key: "tradeName", header: "Nome fantasia" },
      { key: "city", header: "Cidade" },
      { key: "uf", header: "UF" },
    ],
    editableFields: [
      "corporateName",
      "tradeName",
      "establishmentTypeCode",
      "establishmentType",
      "registrationStatusCode",
      "registrationStatus",
      "registrationStatusDate",
      "registrationStatusReasonCode",
      "registrationStatusReason",
      "specialStatus",
      "specialStatusDate",
      "legalNatureCode",
      "legalNature",
      "activityStartDate",
      "mainCnaeCode",
      "mainCnaeDescription",
      "streetType",
      "street",
      "number",
      "complement",
      "neighborhood",
      "cep",
      "uf",
      "cityCode",
      "cityIbgeCode",
      "city",
      "foreignCityName",
      "countryCode",
      "country",
      "primaryPhone",
      "secondaryPhone",
      "fax",
      "email",
      "responsibleQualificationCode",
      "shareCapital",
      "companySizeCode",
      "companySize",
      "responsibleFederativeEntity",
      "optedForSimples",
      "simplesOptionDate",
      "simplesExclusionDate",
      "optedForMei",
      "meiOptionDate",
      "meiExclusionDate",
    ],
    fieldTypes: {
      establishmentTypeCode: "integer",
      registrationStatusCode: "integer",
      registrationStatusReasonCode: "integer",
      legalNatureCode: "integer",
      mainCnaeCode: "integer",
      cityCode: "integer",
      cityIbgeCode: "integer",
      countryCode: "integer",
      responsibleQualificationCode: "integer",
      companySizeCode: "integer",
      shareCapital: "decimal",
      registrationStatusDate: "date",
      specialStatusDate: "date",
      activityStartDate: "date",
      simplesOptionDate: "date",
      simplesExclusionDate: "date",
      meiOptionDate: "date",
      meiExclusionDate: "date",
      optedForSimples: "boolean",
      optedForMei: "boolean",
    },
    fieldMasks: {
      mainCnaeCode: CNAE_MASK,
      cep: CEP_MASK,
      uf: UF_MASK,
      cityIbgeCode: digitsMask(7),
      country: UPPERCASE_MASK,
      primaryPhone: PHONE_MASK,
      secondaryPhone: PHONE_MASK,
      fax: PHONE_MASK,
      shareCapital: CURRENCY_MASK,
    },
    readOnlyFields: ["countryCode", "companySizeCode"],
  },
};
