-- CreateTable
CREATE TABLE "cnpj" (
    "id" UUID NOT NULL,
    "cnpj" VARCHAR(14) NOT NULL,
    "corporate_name" TEXT NOT NULL,
    "trade_name" TEXT,
    "establishment_type_code" INTEGER,
    "establishment_type" TEXT,
    "registration_status_code" INTEGER,
    "registration_status" TEXT,
    "registration_status_date" DATE,
    "registration_status_reason_code" INTEGER,
    "registration_status_reason" TEXT,
    "special_status" TEXT,
    "special_status_date" DATE,
    "legal_nature_code" INTEGER,
    "legal_nature" TEXT,
    "activity_start_date" DATE,
    "main_cnae_code" INTEGER,
    "main_cnae_description" TEXT,
    "secondary_cnaes" JSONB NOT NULL,
    "street_type" TEXT,
    "street" TEXT,
    "number" TEXT,
    "complement" TEXT,
    "neighborhood" TEXT,
    "cep" VARCHAR(8),
    "uf" VARCHAR(2),
    "city_code" INTEGER,
    "city_ibge_code" INTEGER,
    "city" TEXT,
    "foreign_city_name" TEXT,
    "country_code" INTEGER,
    "country" TEXT,
    "primary_phone" TEXT,
    "secondary_phone" TEXT,
    "fax" TEXT,
    "email" TEXT,
    "responsible_qualification_code" INTEGER,
    "share_capital" DECIMAL(18,2),
    "company_size_code" INTEGER,
    "company_size" TEXT,
    "responsible_federative_entity" TEXT,
    "opted_for_simples" BOOLEAN,
    "simples_option_date" DATE,
    "simples_exclusion_date" DATE,
    "opted_for_mei" BOOLEAN,
    "mei_option_date" DATE,
    "mei_exclusion_date" DATE,
    "tax_regimes" JSONB NOT NULL,
    "qsa" JSONB NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "cnpj_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "cnpj_cnpj_key" ON "cnpj"("cnpj");
