-- CreateTable
CREATE TABLE "cnpjs" (
    "id" TEXT NOT NULL,
    "cnpj" TEXT NOT NULL,
    "branchTypeCode" INTEGER NOT NULL,
    "branchTypeDescription" TEXT,
    "legalName" TEXT NOT NULL,
    "tradeName" TEXT,
    "registrationStatusCode" INTEGER NOT NULL,
    "registrationStatusDescription" TEXT,
    "registrationStatusDate" DATE,
    "registrationStatusReasonCode" INTEGER,
    "registrationStatusReasonDescription" TEXT,
    "foreignCityName" TEXT,
    "countryCode" INTEGER,
    "countryName" TEXT,
    "legalNatureCode" INTEGER NOT NULL,
    "legalNatureDescription" TEXT,
    "activityStartDate" DATE,
    "mainCnaeCode" TEXT NOT NULL,
    "mainCnaeDescription" TEXT,
    "streetType" TEXT,
    "street" TEXT,
    "addressNumber" TEXT,
    "complement" TEXT,
    "neighborhood" TEXT,
    "zipCode" TEXT,
    "stateCode" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "siafiCode" TEXT,
    "ibgeCode" TEXT,
    "primaryPhone" TEXT,
    "secondaryPhone" TEXT,
    "fax" TEXT,
    "email" TEXT,
    "responsibleQualificationCode" INTEGER,
    "shareCapital" DECIMAL(18,2) NOT NULL,
    "companySizeCode" INTEGER,
    "companySizeDescription" TEXT,
    "simplesOption" BOOLEAN,
    "simplesOptionDate" DATE,
    "simplesExclusionDate" DATE,
    "meiOption" BOOLEAN,
    "meiOptionDate" DATE,
    "meiExclusionDate" DATE,
    "specialStatus" TEXT,
    "specialStatusDate" DATE,
    "responsibleFederativeEntity" TEXT,
    "secondaryCnaes" JSONB NOT NULL,
    "partners" JSONB NOT NULL,
    "taxRegimes" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "cnpjs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "cnpjs_cnpj_key" ON "cnpjs"("cnpj");
